### ISSUE TITLE
open from dbconfig.yml

### ISSUE THREAD

**Issue by g-hyoga** [g-hyoga/kyuko#14]
スクリプトに直接かいてあるDB情報をdbconfigから読み込むようにする

**Comment by mikoim** [comment]
環境変数 vs 設定ファイル
さぁ，どちらにすべきなのだろうか…

**Comment by g-hyoga** [comment]
DBはファイル
access tokenとかは環境変数
にしますかね...

**Comment by Tamrin007** [comment]
サバでいいんちゃう？
基本的におれらのローカル環境では動かさん（やろう）し

**Comment by g-hyoga** [comment]
でもまぁクローンしたら、ローカルで動かせるのは良い気がするので
(私がクリーンインストールした時のため)

**Comment by mikoim** [comment]
全部環境変数にぶっこんでDockernize不可避（´・ω・） ｽ

**Comment by g-hyoga** [comment]
Dockerも勉強せねば…
