### ISSUE TITLE
同じtweetはできないの忘れていた

### ISSUE THREAD

**Issue by g-hyoga** [g-hyoga/kyuko#35]
Updateからなんかerr返ってこない

対策
tweetに時間を入れる

**Comment by mikoim** [comment]
これは同じ文面をツイートしてもAPIがエラーを返してこないってこと（´・ω・） ｽｶ?

**Comment by g-hyoga** [comment]
そうですね
途中までtweet.Updateのエラー処理忘れてたのでもしかしたら、勘違いかもしれないです

**Comment by mikoim** [comment]
https://twittercommunity.com/t/post-same-tweet-message-multiple-times/5623
どうも，TwitterのAPIはちゃんとエラーを返すらしい（´・ω・） ｽ

**Comment by g-hyoga** [comment]
なんでなんですかね…
まぁ調べておきます…

**Comment by Tamrin007** [comment]
https://github.com/g-hyoga/kyuko/blob/master/go/twitter/twitter.go#L94

↑の`Update()`の中で2番目の返り値を無視せず受け取ってみよう

https://github.com/dghubble/go-twitter/blob/master/twitter/statuses.go#L162

を見ると（↓）返り値の2番目に`http.Response`があるから、レスポンスが見れるはず

詳しく見てないけど、もしかしたらパッケージのバグで403無視してるかも

```go
func (s *StatusService) Update(status string, params *StatusUpdateParams) (*Tweet, *http.Response, error) {
	if params == nil {
		params = &StatusUpdateParams{}
	}
	params.Status = status
	tweet := new(Tweet)
	apiError := new(APIError)
	resp, err := s.sling.New().Post("update.json").BodyForm(params).Receive(tweet, apiError)
	return tweet, resp, relevantError(err, *apiError)
}
```

**Comment by mikoim** [comment]
```go
package main

import (
	"github.com/dghubble/oauth1"
	"github.com/dghubble/go-twitter/twitter"
	"log"
)

func main() {
	config := oauth1.NewConfig("","")
	token := oauth1.NewToken("","")
	httpClient := config.Client(oauth1.NoContext, token)
	client := twitter.NewClient(httpClient)
	_, resp, err := client.Statuses.Update("（*´・ω・） ﾆｬｰﾝ", nil)

	log.Println(resp.Status)
	log.Println(err)
}
```

```
2016/10/31 20:10:08 403 Forbidden
2016/10/31 20:10:08 twitter: 187 Status is a duplicate.
```

普通にエラー返ってくるやん（´・ω・） ｽ (真顔

**Comment by g-hyoga** [comment]
はて....

**Comment by g-hyoga** [comment]
たむりん氏ありがとうございます、私の勘違いだったようだ...

**Comment by g-hyoga** [comment]
まあ時間は入れますかね...?

**Comment by g-hyoga** [comment]
あ、log fileの名前が間違っていた..
違うfile見てた...
ちゃんとエラー吐いてた...

**Comment by mikoim** [comment]
@g-hyoga
![有罪](http://3.bp.blogspot.com/-njLqo2ueOs0/VEETKifyyRI/AAAAAAAAoak/yLLTFiLfD-Y/s800/saiban_yuzai.png)

**Comment by g-hyoga** [comment]
![image](https://cloud.githubusercontent.com/assets/12538942/19854224/3c1bcb6c-9fb1-11e6-9e3d-5f3510af41bf.png)
それでも僕はやってない...

**Comment by Tamrin007** [comment]
ギルティ・・・

**Comment by g-hyoga** [comment]
duplicateならそれでも良い気がしてきた...
