### ISSUE TITLE
はやPがユーザーに休講情報を通知してくれるシステム作るらしい

### ISSUE THREAD

**Issue by g-hyoga** [g-hyoga/kyuko#40]
ToDo
- [ ] DMの取得
    - [x] Twitter APIを調べてDMを取得する
    - [ ] 新規のDMがあるかどうかの確認
    - [ ] 新規DMがあった場合、複数DMがある場合もある事を考慮する
- [x] もらったDMをDBに保存できる状態にする
    - [x] もらうDMはとりあえず  ,(カンマ) 区切りとする
- [ ] DBに情報を保存する
    - [x] 保存するためにDBにtableを作る(正規化してね)
    - [x] テーブルとカラムは適当に考えて（user idと、休講情報を保存できればとりあえずよい）
    - [x] テーブルの作り方は聞いてくれ
    - [x] 保存する情報は、休講時にDMを送るために必要な情報（調べてないけど、user idとか？）とその人の受講している講義名
    - [ ] 各情報を保存する

とりあえずココまで

**Comment by mikoim** [comment]
淫らな生活をさらに淫らなものに…
