### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by mikoim** [g-hyoga/kyuko#7]
[Choose an open source （´・ω・） license.](http://choosealicense.com/)

**Comment by g-hyoga** [comment]
It's up to you(`・ω・)

**Comment by mikoim** [comment]
（´・ω・） つ MIT License

**Comment by Tamrin007** [comment]
👍

**Comment by g-hyoga** [comment]
そーいや、あのよくあるMITの文章ってどっかにあるんですか？

**Comment by Tamrin007** [comment]
https://opensource.org/licenses/MIT

**Comment by Tamrin007** [comment]
http://choosealicense.com/licenses/mit/

**Comment by mikoim** [comment]
1. https://github.com/g-hyoga/kyuko/new/master
1. LICENSE
1. 選ぶ
1. 保存

**Comment by Tamrin007** [comment]
知らんかった。便利。

**Comment by g-hyoga** [comment]
おおお、すごい

**Comment by g-hyoga** [comment]
名前いれてよろしいですか？
